### ISSUE TITLE
Auto-detect stylint installed by `yarn global`

### ISSUE THREAD

**Issue by maranomynet** [HaaLeo/vscode-stylint#1]
Hi. I like the plugin.
It would be nice if it could automatically pick up stylint installed via `yarn global add stylint` so we don't need to hard-code the file path into `stylint.nodePath`.

**Comment by HaaLeo** [comment]
That's a good point. I would love to see a solution that introduces a setting `stylint.packageManager` similar to the [eslint plugin's](https://github.com/Microsoft/vscode-eslint) `eslint.packageManager` setting. 
I do not know when I will have time to implement this. Therefore I'll review/accept PRs for this.

**Comment by maranomynet** [comment]
Does it have to be a setting? Can't the plugin just check the yarn path first and then the npm path?

**Comment by HaaLeo** [comment]
Actually this would work, too 👍.

**Comment by maranomynet** [comment]
I found this: https://github.com/yarnpkg/yarn/issues/2049#issuecomment-263183768

* `%LOCALAPPDATA%/Yarn/config/global` on Windows
* `~/.config/yarn/global` on OSX and non-root Linux
* `/usr/local/share/.config/yarn/global` on Linux if logged in as root

**Comment by maranomynet** [comment]
After a brief look through the source, I don't see how I would change this to make a PR.

**Comment by HaaLeo** [comment]
Actually [`vscode-languageserver`](https://github.com/Microsoft/vscode-languageserver-node) provides a function [`resolveGlobalYarnPath`](https://github.com/Microsoft/vscode-languageserver-node/blob/ae43df6ae2c7503150a7e75b296d2abd8a6ce092/server/src/files.ts#L234) that enables to resolve the global yarn path.
However when using this function a setting is required. Example:
A user uses both, `yarn` and `npm` but stylint is installed gloably with only one package manager (for instance `npm`). Now I could implement the extension to look first for `yarn`'s global path and if that fails for `npm`'s. Now the extension could resolve to the `yarn` path, but would never find `stylint`, because it was installed with `npm`.
Said that, I think it is better to implement this with a setting.
I will try something.
