### ISSUE TITLE
Lazy symbol binding failed

### ISSUE THREAD

**Issue by bzeffren-rms** [HaaLeo/vscode-stylint#7]
| VS Code Version: | vscode-stylint Version: | Installed Stylint Version:  |
| --------------- | ---------------------- | ------------------------- |
|        1.31.0         |            0.1.1             |                    1.5.9       |

# Description

I am getting the following error when Stylint runs on a typed change. I do have have a `.stylintrc` file configured and in the root of my project

```
Stylint: dyld: lazy symbol binding failed: Symbol not found: 
```

## Expected Behavior

It should lint the file and not throw a notification error

## Actual Behavior

# Steps to Reproduce

1. Install Stylint
2. Install VS Code extension
3. Configure `.stylintrc`
4. Open VSCode and edit a `.styl` file
5. Notification appears
![image](https://user-images.githubusercontent.com/45577556/52431865-b207dc80-2ace-11e9-90a0-db9e33894632.png)

# Logs

<details><pre><code>

__ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE Referenced from: /Users/bzeffren/code/rms-one-app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node Expected in: flat namespace dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE Referenced from: /Users/bzeffren/code/rms-one-app/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node Expected in: flat namespace. Please see the 'Stylint' output channel for details.
</code></pre></details>

# Settings
<details><pre><code>

{
  "stylint.alwaysShowStatus": true,
  "stylint.trace.server": "verbose"
}
</code></pre></details>

**Comment by HaaLeo** [comment]
Hi @bzeffren-rms, 
thank you for your report. Unfortunately I could not reproduce this behaviour (I can only check on a windows PC). After searching for that error message I found [this question on Stackoverflow](https://stackoverflow.com/questions/25194862/dyld-lazy-symbol) which seems to be very similar to your issue. So maybe another package causes this issue? 
Sorry that I cannot provide more support, in solving this.
If you (or anybody else) finds a solution for this issue, please let us know in the comments.

**Comment by Leolik** [comment]
I get this error too ((
```
[Error - 12:53:12 AM] Error: dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/leolik/Projects/<...>/src2/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/leolik/Projects/<...>/src2/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace
    at ChildProcess.<anonymous> (/Users/leolik/.vscode/extensions/haaleo.vscode-stylint-0.1.2/server/node_modules/sb-exec/lib/index.js:56:20)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
```

**Comment by szhu** [comment]
Also have been getting this issue since around earlier this month. What's the easiest way to find out the exact command line stylint is running?

**Comment by HaaLeo** [comment]
@szhu Not quite sure what you mean. However the actual stylint call is built and executed in the [`validate()`](https://github.com/HaaLeo/vscode-stylint/blob/master/server/src/stylintModule.ts#L41) method. I think debugging the extension is the easiest way, to find out the exact command line stylint is running. To debug the extension check out the [docs](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#debugging-both-client-and-server):
1. Checkout the repo
1. Run `npm i` in the root
1. In vscode launch the _Launch Client_ debug configuration
1. In vscode launch the _Attach to Server_ debug configuration

Further, I think this bug could be related to the [Node.js update](https://code.visualstudio.com/updates/v1_31#_nodejs-update) they introduced in the latest release of VScode, because of [this issue using native node modules](https://vscode-ppe.azurewebsites.net/docs/extensionAPI/patterns-and-principles#_can-i-use-native-nodejs-modules-with-my-extension).  
Also Microsoft/vscode#68024 seems to be related to this.  
Said that I think getting rid of the calls to `fs.existsSync()` [here](https://github.com/HaaLeo/vscode-stylint/blob/master/server/src/stylintModule.ts#L44) and [here](https://github.com/HaaLeo/vscode-stylint/blob/master/server/src/stylintServer.ts#L380) could fix it.  
But also the usage of [`sb-exec`](https://github.com/HaaLeo/vscode-stylint/blob/master/server/src/stylintModule.ts#L48) could cause similar errors, because it only wraps the native node api.

**Comment by HaaLeo** [comment]
You could try whether uninstalling the extension and then reinstalling it fixes this as a workaround?

**Comment by szhu** [comment]
I spent about 2 hours today trying to figure this out…

Clue 1:
Note that the error message has this snippet:
`Referenced from: .../node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node`

Clue 2:
I googled around for things involving VSCode extensions, node modules, `dyld: lazy symbol binding failed: Symbol not found:`, and various combinations of these. Some of these mention that `npm rebuild package-name` can solve these dyld issues. Example: https://github.com/LinusU/node-appdmg/issues/167#issuecomment-442348409

Given the above, this is how I finally fixed it:
Step 1: `rm -rf node_modules/fsevents/lib/binding/Release`
Step 2: `npm rebuild fsevents`

🎉

**Comment by lukesUbuntu** [comment]
some reason the rebuild fsevents didn't work for me but removing and reinstalling fsevents resolved the issue for me. Thanks for the fix.

**Comment by szhu** [comment]
Sorry, I wasn't clear. The two bullets I gave above are steps, not options -- you must remove the offending file (or all of `fsevents`) before rebuilding. Edited my earlier comment for clarity.

**Comment by HaaLeo** [comment]
Thank you @szhu for digging into this and finding a fix. As soon as the vscode API exposes some functionality to read/check files on the filesystem I will replace the `fs` call with those.  
For now I will publish a new release with a _known issues_ section, mentioning this issue and the possible fix.  
Thank you all for helping out.
